# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  timeout: 5000


development:
  #host: ecopass.cmtxrosnkybq.us-west-2.rds.amazonaws.com
  #port: 5432
  <<: *default
  database: time_weather_development
  pool: 5
  username: postgres
  password: password

 # Connect on a TCP socket. Omitted by default since the client uses a
 # domain socket that doesn't need configuration. Windows does not have
 # domain sockets, so uncomment these lines.
 #host: localhost
 #port: 5432

 # Schema search path. The server defaults to $user,public
 #schema_search_path: myapp,sharedapp,public

 # Minimum log levels, in increasing order:
 #   debug5, debug4, debug3, debug2, debug1,
 #   log, notice, warning, error, fatal, and panic
 # The server defaults to notice.
 #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: utf-8
  database: time_weather_test
  pool: 5
  username: postgres
  password: password

production:
  url: ENV['DATABASE_URL']
  adapter: ENV['DB_ADAPTER']
  encoding: ENV['DB_ENCODING']
  host: ENV['DB_HOST']
  port: ENV['DB_PORT']
  database: ENV['DB_NAME']
  pool: ENV['DB_POOL']
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']
